### PR TITLE
Ammar escalations merger

### PR DESCRIPTION
**Pull request by ahaq0**
Added escalations button and modal that enables functionality for users to escalate pertinent issues within the app. Currently emails are being sent by and to my email we need to authorize the appropriate emails on AWS and replace those.

### CODE REVIEW

**Review by ahmedhamodi — CHANGES_REQUESTED** [review]
Make sure to check the travis CI builds. looks like you forgot to add something to the package.lock.

**Comment by ahaq0** [comment]
Whoops I must've had it installed globally by mistake. Fixed and added the other features. Moved to separate environment variables for the SES service. Should I give everyone my keys on slack or do we want to change the current keys to have access to SES too?

**Comment by ahmedhamodi** [comment]
Good question, I have no preference. By keys, do you mean .env variables @ahaq0? Also, @arsidada do you have any opinions on this?

**Review by ahmedhamodi — APPROVED** [review]
Code looks good to me. Can you just verify the CSS for the button is the same width as the other buttons?
image

**Comment by ahaq0** [comment]
Good catch, fixed in latest commit. Should I go ahead and merge and message everyone my SES keys?

**Comment by ahmedhamodi** [comment]
See if you can add them to the .env file (and load them dynamically from the .env in the app). Then you can message the updated .env to the channel. I can send you the current .env variables if you want.

**Comment by ahaq0** [comment]
Yeah, I currently load them from the .env file. What I meant was if I should send it to everybody. I’ll go ahead and do that.

**Comment by ahmedhamodi** [comment]
Sounds good. You can merge!

**Pull request merged**
